DROP TABLE IF EXISTS TB_BOARD;
CREATE TABLE TB_BOARD (
     POST_ID INTEGER NOT NULL IDENTITY
    , TITLE VARCHAR(150) NULL
    , CONTENTS LONGVARCHAR NULL
    , REG_ID VARCHAR(20) NULL
    , REG_DATE DATE NULL
    , COMMUNITY_ID VARCHAR(16) NULL
    , HIDDEN_INFO VARCHAR(32)
    , HIT_COUNT INTEGER NULL
    , IS_NOTICE BOOLEAN
    , PRIMARY KEY (POST_ID)
);

DROP TABLE IF EXISTS TB_USER;
CREATE TABLE TB_USER (
      USER_ID VARCHAR(50) NOT NULL
    , USER_NAME VARCHAR(50) NOT NULL
    , EN_NAME VARCHAR(20) NULL
    , COMP_PHONE VARCHAR(20) NULL
    , PHONE VARCHAR(20) NULL
    , CELL_PHONE VARCHAR(20) NULL
    , COMPANY VARCHAR(50) NULL
    , JOB_POSITION VARCHAR(20) NULL
    , ASSIGNMENT VARCHAR(20) NULL
    , OFFICER_YN VARCHAR(20) NULL
    , FAX VARCHAR(20) NULL
    , ZIP_CODE VARCHAR(20) NULL
    , ADDRESS VARCHAR(20) NULL
    , COMP_ZIP_CODE VARCHAR(20) NULL
    , COMP_ADDRESS VARCHAR(20) NULL
    , EMAIL VARCHAR(20) NULL
    , DEPT_ID VARCHAR(20) NULL
    , PASSWORD VARCHAR(20) NOT NULL
    , PRIMARY KEY (USER_ID)
);

DROP TABLE IF EXISTS TB_DEPT;
CREATE TABLE TB_DEPT 
(
	deptId int NOT NULL IDENTITY
	, deptName VARCHAR(36) NULL
	, memberCount int NULL
    , PRIMARY KEY (deptId)
);

DROP TABLE IF EXISTS TB_LARGE;
CREATE TABLE TB_LARGE (
    LARGE_ID INTEGER NOT NULL IDENTITY
    , NAME VARCHAR(20) NOT NULL
    , REG_DATE DATE DEFAULT CURRENT_DATE
    , STORY VARCHAR(512) DEFAULT '현재는 유망한 기술 스타트업에서 최고전략책임자(CSO)로 재직하며, 회사의 코스닥 상장(IPO) 준비와 글로벌 시장 진출을 총괄하고 있습니다. 뛰어난 재무 분석 능력과 전략 기획력은 물론, 원어민 수준의 영어와 비즈니스 회화가 가능한 중국어 실력까지 겸비한 김철수 씨는 명실상부한 대한민국 미래 성장을 이끌어갈 핵심 리더로 평가받고 있습니다.'
    , STATUS INTEGER DEFAULT 1
    , PRIMARY KEY (LARGE_ID)
);

DROP TABLE IF EXISTS TB_TEST_DATA_TYPE;
CREATE TABLE TB_TEST_DATA_TYPE (
    ID INTEGER NOT NULL IDENTITY,
    STRING_VALUE VARCHAR(200) NULL,
    INT_VALUE INTEGER NULL,
    BOOLEAN_VALUE BOOLEAN NULL,
    LONG_VALUE BIGINT NULL,
    FLOAT_VALUE FLOAT NULL,
    DOUBLE_VALUE DOUBLE NULL,
    BIG_DECIMAL_VALUE DECIMAL(19, 4) NULL,
    DATE_VALUE DATE NULL, 
    TIME_VALUE TIMESTAMP NULL,
    DATETIME_VALUE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    BYTES_VALUE BLOB NULL,
    PRIMARY KEY (ID)
);
